var searchData=
[
  ['sau_20functions_0',['SAU Functions',['../group___c_m_s_i_s___core___s_a_u_functions.html',1,'']]],
  ['sigmoid_20svm_1',['Sigmoid SVM',['../group__sigmoidsvm.html',1,'']]],
  ['sine_2',['Sine',['../group__sin.html',1,'']]],
  ['sine_20cosine_3',['Sine Cosine',['../group___sin_cos.html',1,'']]],
  ['spi_4',['SPI',['../group___s_p_i.html',1,'']]],
  ['spi_20baudrate_20prescaler_5',['SPI BaudRate Prescaler',['../group___s_p_i___baud_rate___prescaler.html',1,'']]],
  ['spi_20clock_20phase_6',['SPI Clock Phase',['../group___s_p_i___clock___phase.html',1,'']]],
  ['spi_20clock_20polarity_7',['SPI Clock Polarity',['../group___s_p_i___clock___polarity.html',1,'']]],
  ['spi_20crc_20calculation_8',['SPI CRC Calculation',['../group___s_p_i___c_r_c___calculation.html',1,'']]],
  ['spi_20crc_20length_9',['SPI CRC Length',['../group___s_p_i___c_r_c__length.html',1,'']]],
  ['spi_20data_20size_10',['SPI Data Size',['../group___s_p_i___data___size.html',1,'']]],
  ['spi_20direction_20mode_11',['SPI Direction Mode',['../group___s_p_i___direction.html',1,'']]],
  ['spi_20error_20code_12',['SPI Error Code',['../group___s_p_i___error___code.html',1,'']]],
  ['spi_20exported_20constants_13',['SPI Exported Constants',['../group___s_p_i___exported___constants.html',1,'']]],
  ['spi_20exported_20macros_14',['SPI Exported Macros',['../group___s_p_i___exported___macros.html',1,'']]],
  ['spi_20exported_20types_15',['SPI Exported Types',['../group___s_p_i___exported___types.html',1,'']]],
  ['spi_20fifo_20reception_20threshold_16',['SPI FIFO Reception Threshold',['../group___s_p_i___f_i_f_o__reception__threshold.html',1,'']]],
  ['spi_20flags_20definition_17',['SPI Flags Definition',['../group___s_p_i___flags__definition.html',1,'']]],
  ['spi_20interrupt_20definition_18',['SPI Interrupt Definition',['../group___s_p_i___interrupt__definition.html',1,'']]],
  ['spi_20mode_19',['SPI Mode',['../group___s_p_i___mode.html',1,'']]],
  ['spi_20msb_20lsb_20transmission_20',['SPI MSB LSB Transmission',['../group___s_p_i___m_s_b___l_s_b__transmission.html',1,'']]],
  ['spi_20nss_20pulse_20mode_21',['SPI NSS Pulse Mode',['../group___s_p_i___n_s_s_p___mode.html',1,'']]],
  ['spi_20private_20macros_22',['SPI Private Macros',['../group___s_p_i___private___macros.html',1,'']]],
  ['spi_20reception_20fifo_20status_20level_23',['SPI Reception FIFO Status Level',['../group___s_p_i__reception__fifo__status__level.html',1,'']]],
  ['spi_20slave_20select_20management_24',['SPI Slave Select Management',['../group___s_p_i___slave___select__management.html',1,'']]],
  ['spi_20ti_20mode_25',['SPI TI Mode',['../group___s_p_i___t_i__mode.html',1,'']]],
  ['spi_20transmission_20fifo_20status_20level_26',['SPI Transmission FIFO Status Level',['../group___s_p_i__transmission__fifo__status__level.html',1,'']]],
  ['spi_5fexported_5ffunctions_27',['SPI_Exported_Functions',['../group___s_p_i___exported___functions.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup1_28',['SPI_Exported_Functions_Group1',['../group___s_p_i___exported___functions___group1.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup2_29',['SPI_Exported_Functions_Group2',['../group___s_p_i___exported___functions___group2.html',1,'']]],
  ['spi_5fexported_5ffunctions_5fgroup3_30',['SPI_Exported_Functions_Group3',['../group___s_p_i___exported___functions___group3.html',1,'']]],
  ['spiex_31',['SPIEx',['../group___s_p_i_ex.html',1,'']]],
  ['spiex_5fexported_5ffunctions_32',['SPIEx_Exported_Functions',['../group___s_p_i_ex___exported___functions.html',1,'']]],
  ['spiex_5fexported_5ffunctions_5fgroup1_33',['SPIEx_Exported_Functions_Group1',['../group___s_p_i_ex___exported___functions___group1.html',1,'']]],
  ['square_20root_34',['Square Root',['../group___s_q_r_t.html',1,'']]],
  ['standard_20deviation_35',['Standard deviation',['../group___s_t_d.html',1,'']]],
  ['statistics_20functions_36',['Statistics Functions',['../group__group_stats.html',1,'']]],
  ['status_20and_20control_20registers_37',['Status and Control Registers',['../group___c_m_s_i_s___c_o_r_e.html',1,'']]],
  ['stm32f722xx_38',['Stm32f722xx',['../group__stm32f722xx.html',1,'']]],
  ['stm32f7xx_39',['Stm32f7xx',['../group__stm32f7xx.html',1,'']]],
  ['stm32f7xx_5fhal_5fdriver_40',['STM32F7xx_HAL_Driver',['../group___s_t_m32_f7xx___h_a_l___driver.html',1,'']]],
  ['stm32f7xx_5fll_5fusb_5fdriver_41',['STM32F7xx_LL_USB_DRIVER',['../group___s_t_m32_f7xx___l_l___u_s_b___d_r_i_v_e_r.html',1,'']]],
  ['stm32f7xx_5fsystem_42',['Stm32f7xx_system',['../group__stm32f7xx__system.html',1,'']]],
  ['stm32f7xx_5fsystem_5fexported_5fconstants_43',['STM32F7xx_System_Exported_Constants',['../group___s_t_m32_f7xx___system___exported___constants.html',1,'']]],
  ['stm32f7xx_5fsystem_5fexported_5ffunctions_44',['STM32F7xx_System_Exported_Functions',['../group___s_t_m32_f7xx___system___exported___functions.html',1,'']]],
  ['stm32f7xx_5fsystem_5fexported_5fmacros_45',['STM32F7xx_System_Exported_Macros',['../group___s_t_m32_f7xx___system___exported___macros.html',1,'']]],
  ['stm32f7xx_5fsystem_5fexported_5fvariables_46',['STM32F7xx_System_Exported_Variables',['../group___s_t_m32_f7xx___system___exported___variables.html',1,'']]],
  ['stm32f7xx_5fsystem_5fincludes_47',['STM32F7xx_System_Includes',['../group___s_t_m32_f7xx___system___includes.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5fdefines_48',['STM32F7xx_System_Private_Defines',['../group___s_t_m32_f7xx___system___private___defines.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5ffunctionprototypes_49',['STM32F7xx_System_Private_FunctionPrototypes',['../group___s_t_m32_f7xx___system___private___function_prototypes.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5ffunctions_50',['STM32F7xx_System_Private_Functions',['../group___s_t_m32_f7xx___system___private___functions.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5fincludes_51',['STM32F7xx_System_Private_Includes',['../group___s_t_m32_f7xx___system___private___includes.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5fmacros_52',['STM32F7xx_System_Private_Macros',['../group___s_t_m32_f7xx___system___private___macros.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5ftypesdefinitions_53',['STM32F7xx_System_Private_TypesDefinitions',['../group___s_t_m32_f7xx___system___private___types_definitions.html',1,'']]],
  ['stm32f7xx_5fsystem_5fprivate_5fvariables_54',['STM32F7xx_System_Private_Variables',['../group___s_t_m32_f7xx___system___private___variables.html',1,'']]],
  ['support_20functions_55',['Support Functions',['../group__group_support.html',1,'']]],
  ['svm_20functions_56',['SVM Functions',['../group__group_s_v_m.html',1,'']]],
  ['system_20clock_20source_20status_57',['System Clock Source Status',['../group___r_c_c___system___clock___source___status.html',1,'']]],
  ['system_20control_20block_20_28scb_29_58',['System Control Block (SCB)',['../group___c_m_s_i_s___s_c_b.html',1,'']]],
  ['system_20controls_20not_20in_20scb_20_28scnscb_29_59',['System Controls not in SCB (SCnSCB)',['../group___c_m_s_i_s___s_cn_s_c_b.html',1,'']]],
  ['system_20tick_20timer_20_28systick_29_60',['System Tick Timer (SysTick)',['../group___c_m_s_i_s___sys_tick.html',1,'']]],
  ['systick_20functions_61',['SysTick Functions',['../group___c_m_s_i_s___core___sys_tick_functions.html',1,'']]]
];
